TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.3
  max_vel_theta: 3.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  holonomic_robot: false
  meter_scoreing: false
